"""Static reference data for the seeded demonstration estate."""

from __future__ import annotations

from app.core.enums import (
    ContextType,
    IndicatorType,
    IntegrationKind,
    IntegrationStatus,
    ResponseAction,
    Severity,
)

# --------------------------------------------------------------------- identities
# (username, display name, department, role, location, privileged, manager)
IDENTITIES: tuple[tuple[str, str, str, str, str, bool, str], ...] = (
    (
        "alex.mercer",
        "Alex Mercer",
        "Engineering",
        "Senior Frontend Engineer",
        "San Francisco",
        False,
        "Dana Whitfield",
    ),
    (
        "jordan.lee",
        "Jordan Lee",
        "Engineering",
        "Frontend Engineer",
        "San Francisco",
        False,
        "Dana Whitfield",
    ),
    ("chloe.dupont", "Chloe Dupont", "Engineering", "Software Engineer", "Paris", False, "Dana Whitfield"),
    (
        "ravi.anand",
        "Ravi Anand",
        "Engineering",
        "Staff Frontend Engineer",
        "Bangalore",
        False,
        "Dana Whitfield",
    ),
    (
        "dana.whitfield",
        "Dana Whitfield",
        "Engineering",
        "Engineering Manager",
        "San Francisco",
        False,
        "Mark Robinson",
    ),
    ("sarah.connor", "Sarah Connor", "Infrastructure", "Lead DevOps Engineer", "Austin", True, "Alan Turing"),
    (
        "liam.smith",
        "Liam Smith",
        "Infrastructure",
        "Site Reliability Engineer",
        "Dublin",
        True,
        "Alan Turing",
    ),
    ("mei.tanaka", "Mei Tanaka", "Infrastructure", "Site Reliability Engineer", "Tokyo", True, "Alan Turing"),
    (
        "omar.haddad",
        "Omar Haddad",
        "Infrastructure",
        "Cloud Platform Engineer",
        "Berlin",
        True,
        "Alan Turing",
    ),
    (
        "priya.patel",
        "Priya Patel",
        "Core Platform",
        "Cloud Backend Architect",
        "London",
        True,
        "Mark Robinson",
    ),
    (
        "lucas.muller",
        "Lucas Muller",
        "Core Platform",
        "Distributed Systems Engineer",
        "Berlin",
        False,
        "Mark Robinson",
    ),
    ("ana.silva", "Ana Silva", "Core Platform", "Backend Engineer", "Lisbon", False, "Mark Robinson"),
    ("marcus.vance", "Marcus Vance", "Finance", "Financial Controller", "New York", False, "Helen Park"),
    ("noah.garcia", "Noah Garcia", "Sales", "Senior Account Executive", "Chicago", False, "Helen Park"),
    ("grace.oyelaran", "Grace Oyelaran", "Finance", "Senior Accountant", "New York", False, "Helen Park"),
    (
        "elena.rostova",
        "Elena Rostova",
        "Analytics",
        "Staff Data Scientist",
        "Amsterdam",
        False,
        "Sofia Marchetti",
    ),
    ("sophia.chen", "Sophia Chen", "Analytics", "BI Analyst", "Singapore", False, "Sofia Marchetti"),
    ("tom.becker", "Tom Becker", "Analytics", "Data Engineer", "Toronto", False, "Sofia Marchetti"),
    ("david.kim", "David Kim", "People Ops", "HR Operations Director", "Seattle", False, "Mark Robinson"),
    (
        "aisha.nkemelu",
        "Aisha Nkemelu",
        "People Ops",
        "People Operations Partner",
        "Seattle",
        False,
        "David Kim",
    ),
    ("victor.ross", "Victor Ross", "Legal", "Corporate Counsel", "New York", False, "Mark Robinson"),
    ("nina.kovac", "Nina Kovac", "Security", "Senior Security Engineer", "Zagreb", True, "Alan Turing"),
    ("felix.andersen", "Felix Andersen", "Security", "Detection Engineer", "Copenhagen", True, "Alan Turing"),
    (
        "svc.data-pipeline",
        "Data Pipeline Service",
        "Core Platform",
        "Service Account",
        "us-east-1",
        True,
        "Mark Robinson",
    ),
)

SERVICE_ACCOUNTS = {"svc.data-pipeline"}

# ------------------------------------------------------------------------- assets
# (key, name, category, tier, env, owner, pii, pci, phi, crown jewel, records, scopes)
ASSETS: tuple[tuple, ...] = (
    (
        "github_repo_webapp",
        "Web App Repository",
        "source_code",
        1,
        "development",
        "Engineering",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "github_repo_backend",
        "Backend Monorepo",
        "source_code",
        2,
        "development",
        "Core Platform",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "jira_board_sprint",
        "Jira Sprint Board",
        "application",
        1,
        "production",
        "Engineering",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "figma_designs",
        "Figma Design Library",
        "application",
        1,
        "production",
        "Engineering",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "npm_registry_internal",
        "Internal NPM Registry",
        "application",
        2,
        "production",
        "Engineering",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "ci_pipeline_frontend",
        "Frontend CI Pipeline",
        "application",
        2,
        "production",
        "Engineering",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "staging_api_gateway",
        "Staging API Gateway",
        "application",
        2,
        "staging",
        "Core Platform",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "sso_okta_gateway",
        "Okta SSO Gateway",
        "identity",
        2,
        "production",
        "Security",
        False,
        False,
        False,
        False,
        0,
        ["SOC 2"],
    ),
    (
        "kubernetes_cluster_dev",
        "Dev Kubernetes Cluster",
        "application",
        2,
        "development",
        "Infrastructure",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "kubernetes_cluster_prod",
        "Production Kubernetes",
        "application",
        4,
        "production",
        "Infrastructure",
        False,
        False,
        False,
        True,
        0,
        ["SOC 2", "PCI DSS"],
    ),
    (
        "terraform_staging",
        "Terraform Staging State",
        "application",
        2,
        "staging",
        "Infrastructure",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "datadog_dashboards",
        "Datadog Dashboards",
        "application",
        1,
        "production",
        "Infrastructure",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "aws_ec2_dev",
        "AWS EC2 Development",
        "application",
        2,
        "development",
        "Infrastructure",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "bastion_host_eu",
        "EU Bastion Host",
        "application",
        3,
        "production",
        "Infrastructure",
        False,
        False,
        False,
        False,
        0,
        ["SOC 2"],
    ),
    (
        "aws_management_console",
        "AWS Management Console",
        "iam",
        3,
        "production",
        "Infrastructure",
        False,
        False,
        False,
        False,
        0,
        ["SOC 2"],
    ),
    (
        "iam_role_security_auditor",
        "IAM Security Auditor Role",
        "iam",
        4,
        "production",
        "Security",
        False,
        False,
        False,
        False,
        0,
        ["SOC 2"],
    ),
    (
        "aws_iam_policy_admin_attach",
        "AWS IAM Admin Policy",
        "iam",
        5,
        "production",
        "Security",
        False,
        False,
        False,
        True,
        0,
        ["SOC 2", "ISO 27001"],
    ),
    (
        "cloudtrail_audit_log_stream",
        "CloudTrail Audit Stream",
        "audit",
        5,
        "production",
        "Security",
        False,
        False,
        False,
        True,
        0,
        ["SOC 2", "PCI DSS", "ISO 27001"],
    ),
    (
        "prod_ssh_keys_vault",
        "Production SSH Key Vault",
        "secret_store",
        5,
        "production",
        "Security",
        False,
        False,
        False,
        True,
        0,
        ["SOC 2", "ISO 27001"],
    ),
    (
        "vault_policy_admin",
        "HashiCorp Vault Policy Admin",
        "secret_store",
        4,
        "production",
        "Security",
        False,
        False,
        False,
        False,
        0,
        ["SOC 2"],
    ),
    (
        "gcp_secret_manager_db_keys",
        "GCP Secret Manager — DB Keys",
        "secret_store",
        4,
        "production",
        "Core Platform",
        False,
        True,
        False,
        False,
        0,
        ["PCI DSS"],
    ),
    (
        "gcp_iam_service_account_token",
        "GCP Service Account Token",
        "iam",
        3,
        "production",
        "Core Platform",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "gcp_resourcemanager_organization_admin",
        "GCP Organization Admin",
        "iam",
        5,
        "production",
        "Security",
        False,
        False,
        False,
        True,
        0,
        ["SOC 2", "ISO 27001"],
    ),
    (
        "prod_customer_sql_replica",
        "Customer SQL Replica",
        "database",
        4,
        "production",
        "Core Platform",
        True,
        False,
        False,
        False,
        1_240_000,
        ["GDPR", "SOC 2"],
    ),
    (
        "postgres_user_db_dev",
        "Dev User Postgres",
        "database",
        2,
        "development",
        "Core Platform",
        False,
        False,
        False,
        False,
        4_000,
        [],
    ),
    (
        "prod_payment_vault_metadata",
        "Payment Vault Metadata",
        "database",
        4,
        "production",
        "Finance",
        True,
        True,
        False,
        True,
        342_000,
        ["PCI DSS", "GDPR"],
    ),
    (
        "internal_schema_docs_customer_pii",
        "Customer PII Schema Docs",
        "application",
        3,
        "production",
        "Core Platform",
        False,
        False,
        False,
        False,
        0,
        ["GDPR"],
    ),
    (
        "crown_jewel_customer_pii_export",
        "Customer PII Master Export",
        "object_store",
        5,
        "production",
        "Core Platform",
        True,
        True,
        False,
        True,
        2_480_000,
        ["GDPR", "PCI DSS", "SOC 2"],
    ),
    (
        "prod_datalake_s3",
        "Production Data Lake (S3)",
        "object_store",
        4,
        "production",
        "Analytics",
        True,
        False,
        False,
        False,
        8_400_000,
        ["GDPR"],
    ),
    (
        "snowflake_titan_lake",
        "Snowflake — Project Titan",
        "database",
        4,
        "production",
        "Analytics",
        True,
        False,
        False,
        False,
        3_100_000,
        ["GDPR"],
    ),
    (
        "customer_analytics_warehouse",
        "Customer Analytics Warehouse",
        "database",
        4,
        "production",
        "Analytics",
        True,
        False,
        False,
        False,
        5_600_000,
        ["GDPR"],
    ),
    (
        "snowflake_bi_marts",
        "Snowflake BI Marts",
        "database",
        2,
        "production",
        "Analytics",
        False,
        False,
        False,
        False,
        900_000,
        [],
    ),
    (
        "tableau_dashboards",
        "Tableau Dashboards",
        "application",
        1,
        "production",
        "Analytics",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "dbt_analytics_models",
        "dbt Analytics Models",
        "application",
        2,
        "production",
        "Analytics",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "metabase_sql_runner",
        "Metabase SQL Runner",
        "application",
        2,
        "production",
        "Analytics",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "kafka_staging_cluster",
        "Kafka Staging Cluster",
        "application",
        2,
        "staging",
        "Core Platform",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "grpc_api_specs",
        "gRPC API Specifications",
        "application",
        1,
        "production",
        "Core Platform",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "service_mesh_config",
        "Service Mesh Configuration",
        "application",
        3,
        "production",
        "Core Platform",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "netsuite_erp",
        "NetSuite ERP",
        "application",
        3,
        "production",
        "Finance",
        False,
        False,
        False,
        False,
        0,
        ["SOC 2"],
    ),
    (
        "quarterly_budget_sheets",
        "Quarterly Budget Sheets",
        "application",
        3,
        "production",
        "Finance",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "payroll_internal_app",
        "Payroll System",
        "application",
        4,
        "production",
        "People Ops",
        True,
        False,
        False,
        True,
        24_000,
        ["GDPR", "SOC 2"],
    ),
    (
        "stripe_reporting_api",
        "Stripe Reporting API",
        "application",
        3,
        "production",
        "Finance",
        True,
        True,
        False,
        False,
        180_000,
        ["PCI DSS"],
    ),
    (
        "workday_portal",
        "Workday HRIS",
        "application",
        3,
        "production",
        "People Ops",
        True,
        False,
        True,
        False,
        24_000,
        ["GDPR", "HIPAA"],
    ),
    (
        "greenhouse_ats",
        "Greenhouse ATS",
        "application",
        2,
        "production",
        "People Ops",
        True,
        False,
        False,
        False,
        62_000,
        ["GDPR"],
    ),
    (
        "notion_handbook",
        "Company Handbook",
        "application",
        1,
        "production",
        "People Ops",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "slack_admin_panel",
        "Slack Admin Panel",
        "application",
        2,
        "production",
        "People Ops",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "salesforce_crm_pipeline",
        "Salesforce CRM Pipeline",
        "application",
        3,
        "production",
        "Sales",
        True,
        False,
        False,
        False,
        410_000,
        ["GDPR"],
    ),
    (
        "gong_call_recordings",
        "Gong Call Recordings",
        "application",
        2,
        "production",
        "Sales",
        True,
        False,
        False,
        False,
        88_000,
        ["GDPR"],
    ),
    (
        "pricing_playbook_confidential",
        "Confidential Pricing Playbook",
        "application",
        4,
        "production",
        "Sales",
        False,
        False,
        False,
        True,
        0,
        [],
    ),
    (
        "customer_contact_master_list",
        "Customer Contact Master List",
        "database",
        4,
        "production",
        "Sales",
        True,
        False,
        False,
        True,
        880_000,
        ["GDPR"],
    ),
    (
        "gdrive_external_share",
        "Google Drive External Share",
        "object_store",
        4,
        "production",
        "Security",
        True,
        False,
        False,
        False,
        0,
        ["GDPR"],
    ),
    (
        "ironclad_contracts",
        "Ironclad Contract Repository",
        "application",
        3,
        "production",
        "Legal",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "legal_matter_tracker",
        "Legal Matter Tracker",
        "application",
        3,
        "production",
        "Legal",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "docusign_envelopes",
        "DocuSign Envelopes",
        "application",
        2,
        "production",
        "Legal",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
    (
        "splunk_search_head",
        "Splunk Search Head",
        "application",
        3,
        "production",
        "Security",
        False,
        False,
        False,
        False,
        0,
        ["SOC 2"],
    ),
    (
        "crowdstrike_console",
        "CrowdStrike Console",
        "application",
        3,
        "production",
        "Security",
        False,
        False,
        False,
        False,
        0,
        ["SOC 2"],
    ),
    (
        "email_suite",
        "Corporate Email Suite",
        "application",
        2,
        "production",
        "Security",
        True,
        False,
        False,
        False,
        0,
        ["GDPR"],
    ),
    (
        "wiki_internal",
        "Internal Wiki",
        "application",
        1,
        "production",
        "Engineering",
        False,
        False,
        False,
        False,
        0,
        [],
    ),
)

# ---------------------------------------------------------------------- contexts
# (username, type, title, description, ticket, days back, days forward, factor, approver, resources)
CONTEXTS: tuple[tuple, ...] = (
    (
        "priya.patel",
        ContextType.PROJECT_TRANSFER,
        "Project Titan data-lake migration lead",
        "Assigned as technical lead for the Titan migration; requires Tier-4 warehouse access "
        "for the duration of the cutover.",
        "CHG-2024-9182",
        12,
        30,
        0.22,
        "Mark Robinson (VP Engineering)",
        ["prod_datalake_s3", "customer_analytics_warehouse", "snowflake_titan_lake"],
    ),
    (
        "sarah.connor",
        ContextType.ON_CALL_ROTATION,
        "Tier-1 production primary on-call",
        "Primary on-call for production incidents; elevated cluster and bastion access expected.",
        "INC-SCHEDULE-WK38",
        3,
        4,
        0.35,
        "Alan Turing (DevOps Manager)",
        ["kubernetes_cluster_prod", "bastion_host_eu"],
    ),
    (
        "nina.kovac",
        ContextType.INCIDENT_RESPONSE,
        "Active incident response authorisation",
        "Standing authorisation to inspect security tooling and audit streams during triage.",
        "IR-STANDING-SEC",
        60,
        120,
        0.4,
        "Alan Turing (DevOps Manager)",
        ["splunk_search_head", "crowdstrike_console", "iam_role_security_auditor"],
    ),
    (
        "omar.haddad",
        ContextType.MAINTENANCE_WINDOW,
        "Quarterly cluster maintenance window",
        "Approved window for production cluster upgrades and node rotation.",
        "CHG-2024-9355",
        1,
        2,
        0.3,
        "Alan Turing (DevOps Manager)",
        ["kubernetes_cluster_prod", "terraform_staging"],
    ),
)

# ------------------------------------------------------------------------- rules
BUILTIN_RULES: tuple[dict, ...] = (
    {
        "slug": "audit-log-destruction",
        "name": "Audit log destruction",
        "description": "Deletion or disabling of audit telemetry. Never legitimate from a "
        "workforce identity and exempt from contextual suppression.",
        "category": "anti_tamper",
        "severity": Severity.CRITICAL,
        "conditions": {"field": "action", "op": "in", "value": ["delete_audit_logs", "disable_logging"]},
        "risk_boost": 40.0,
        "mitre_techniques": ["T1562.008", "T1070"],
        "recommended_actions": [ResponseAction.QUARANTINE_SESSION.value, ResponseAction.ESCALATE.value],
        "suppress_when_context": False,
    },
    {
        "slug": "crown-jewel-bulk-export",
        "name": "Crown-jewel bulk export",
        "description": "A Tier-5 asset exported in bulk, the terminal step of most exfiltration chains.",
        "category": "exfiltration",
        "severity": Severity.CRITICAL,
        "conditions": {
            "all": [
                {"field": "sensitivity_level", "op": "gte", "value": 5},
                {
                    "field": "action",
                    "op": "in",
                    "value": ["export", "export_all", "download", "share_external"],
                },
            ]
        },
        "risk_boost": 35.0,
        "mitre_techniques": ["T1020", "T1048"],
        "recommended_actions": [ResponseAction.QUARANTINE_SESSION.value, ResponseAction.REVOKE_TOKENS.value],
        "suppress_when_context": False,
    },
    {
        "slug": "off-hours-privileged-escalation",
        "name": "Off-hours privilege escalation",
        "description": "Role assumption or IAM modification outside working hours.",
        "category": "privilege",
        "severity": Severity.HIGH,
        "conditions": {
            "all": [
                {"field": "is_off_hours", "op": "is_true"},
                {
                    "field": "action",
                    "op": "in",
                    "value": ["sudo", "assume_role", "iam_modify", "attach_policy", "grant_permission"],
                },
            ]
        },
        "risk_boost": 22.0,
        "mitre_techniques": ["T1548", "T1098"],
        "recommended_actions": [ResponseAction.STEP_UP_MFA.value],
    },
    {
        "slug": "impossible-travel-session",
        "name": "Impossible travel between sessions",
        "description": "Geo-velocity saturated — consecutive sessions imply a physically impossible journey.",
        "category": "identity",
        "severity": Severity.HIGH,
        "conditions": {"field": "vectors.geovelocity", "op": "gte", "value": 80},
        "risk_boost": 28.0,
        "mitre_techniques": ["T1078", "T1078.004"],
        "recommended_actions": [ResponseAction.STEP_UP_MFA.value, ResponseAction.REVOKE_TOKENS.value],
    },
    {
        "slug": "secret-store-access-anomaly",
        "name": "Anomalous secret-store access",
        "description": "Secret manager or key vault read by an identity outside its baseline.",
        "category": "credential",
        "severity": Severity.HIGH,
        "conditions": {
            "all": [
                {
                    "any": [
                        {"field": "resource", "op": "contains", "value": "secret"},
                        {"field": "resource", "op": "contains", "value": "vault"},
                        {"field": "resource", "op": "contains", "value": "credential"},
                    ]
                },
                {"field": "vectors.resource", "op": "gte", "value": 55},
            ]
        },
        "risk_boost": 24.0,
        "mitre_techniques": ["T1555", "T1552"],
        "recommended_actions": [ResponseAction.STEP_UP_MFA.value, ResponseAction.NOTIFY_MANAGER.value],
    },
    {
        "slug": "mass-record-extraction",
        "name": "Mass record extraction",
        "description": "A single operation touching more than 50,000 records.",
        "category": "exfiltration",
        "severity": Severity.HIGH,
        "conditions": {"field": "record_count", "op": "gte", "value": 50000},
        "risk_boost": 26.0,
        "mitre_techniques": ["T1020", "T1005"],
        "recommended_actions": [ResponseAction.OPEN_TICKET.value],
    },
    {
        "slug": "large-egress-volume",
        "name": "Large outbound transfer",
        "description": "More than 250 MB moved in a single operation.",
        "category": "exfiltration",
        "severity": Severity.MEDIUM,
        "conditions": {"field": "bytes_transferred", "op": "gte", "value": 250000000},
        "risk_boost": 18.0,
        "mitre_techniques": ["T1048", "T1567"],
        "recommended_actions": [ResponseAction.OPEN_TICKET.value],
    },
    {
        "slug": "cross-department-pii-access",
        "name": "Cross-department PII access",
        "description": "PII-scoped resources reached by an identity whose cohort never touches them.",
        "category": "behavioural",
        "severity": Severity.HIGH,
        "conditions": {
            "all": [
                {"field": "vectors.peer_divergence", "op": "gte", "value": 70},
                {"field": "sensitivity_level", "op": "gte", "value": 4},
            ]
        },
        "risk_boost": 20.0,
        "mitre_techniques": ["T1213", "T1530"],
        "recommended_actions": [ResponseAction.NOTIFY_MANAGER.value],
    },
    {
        "slug": "unrecognised-device-privileged",
        "name": "Privileged action from unrecognised device",
        "description": "A privileged operation from a device fingerprint never seen for this identity.",
        "category": "identity",
        "severity": Severity.HIGH,
        "conditions": {
            "all": [
                {"field": "vectors.device", "op": "gte", "value": 50},
                {"field": "vectors.privilege", "op": "gte", "value": 60},
            ]
        },
        "risk_boost": 22.0,
        "mitre_techniques": ["T1078"],
        "recommended_actions": [ResponseAction.STEP_UP_MFA.value],
    },
    {
        "slug": "threat-intel-match",
        "name": "Threat intelligence indicator match",
        "description": "A network artefact matched an active indicator of compromise.",
        "category": "intel",
        "severity": Severity.HIGH,
        "conditions": {"field": "vectors.intel", "op": "gte", "value": 60},
        "risk_boost": 25.0,
        "mitre_techniques": ["T1078"],
        "recommended_actions": [ResponseAction.QUARANTINE_SESSION.value],
        "suppress_when_context": False,
    },
    {
        "slug": "repeated-authentication-failure",
        "name": "Repeated authentication failure",
        "description": "Denied authentication, consistent with credential guessing or spraying.",
        "category": "credential",
        "severity": Severity.MEDIUM,
        "conditions": {
            "all": [
                {"field": "event_type", "op": "eq", "value": "AUTHENTICATION"},
                {"field": "outcome", "op": "in", "value": ["DENIED", "FAILURE"]},
            ]
        },
        "risk_boost": 12.0,
        "mitre_techniques": ["T1110"],
        "recommended_actions": [ResponseAction.STEP_UP_MFA.value],
    },
    {
        "slug": "weekend-production-access",
        "name": "Weekend production access",
        "description": "Production Tier-4+ access on a weekend without an approved window.",
        "category": "behavioural",
        "severity": Severity.MEDIUM,
        "conditions": {
            "all": [
                {"field": "is_weekend", "op": "is_true"},
                {"field": "sensitivity_level", "op": "gte", "value": 4},
            ]
        },
        "risk_boost": 14.0,
        "mitre_techniques": ["T1078"],
        "recommended_actions": [ResponseAction.NOTIFY_MANAGER.value],
    },
)

# --------------------------------------------------------------------- playbooks
PLAYBOOKS: tuple[dict, ...] = (
    {
        "slug": "confirmed-account-compromise",
        "name": "Confirmed account compromise",
        "description": "Full containment for an identity believed to be under adversary control.",
        "category": "containment",
        "estimated_minutes": 12,
        "requires_approval": True,
        "steps": [
            {
                "action": ResponseAction.QUARANTINE_SESSION.value,
                "label": "Terminate all active sessions",
                "description": "Kill IdP sessions and isolate the endpoint.",
            },
            {
                "action": ResponseAction.REVOKE_TOKENS.value,
                "label": "Revoke tokens",
                "description": "Invalidate refresh tokens and OAuth grants.",
            },
            {
                "action": ResponseAction.SUSPEND_API_KEYS.value,
                "label": "Suspend API keys",
                "description": "Disable machine credentials issued to this identity.",
            },
            {
                "action": ResponseAction.DISABLE_ACCOUNT.value,
                "label": "Disable the account",
                "description": "Pending identity verification by the reporting manager.",
            },
            {
                "action": ResponseAction.NOTIFY_MANAGER.value,
                "label": "Notify the manager",
                "description": "Out-of-band confirmation of the user's whereabouts.",
            },
            {
                "action": ResponseAction.ESCALATE.value,
                "label": "Escalate to Tier-3",
                "description": "Hand off to incident response with the forensic dossier.",
            },
        ],
        "trigger_conditions": {
            "all": [
                {"field": "risk_score", "op": "gte", "value": 85},
                {"field": "anti_tamper", "op": "is_true"},
            ]
        },
    },
    {
        "slug": "suspected-insider-collection",
        "name": "Suspected insider data collection",
        "description": "Measured response to staged collection where attribution is not yet certain.",
        "category": "investigation",
        "estimated_minutes": 25,
        "requires_approval": True,
        "steps": [
            {
                "action": ResponseAction.OPEN_TICKET.value,
                "label": "Open an investigation case",
                "description": "Create a tracked case with the evidence bundle attached.",
            },
            {
                "action": ResponseAction.STEP_UP_MFA.value,
                "label": "Force step-up MFA",
                "description": "Confirm the human behind the session without tipping them off.",
            },
            {
                "action": ResponseAction.NOTIFY_MANAGER.value,
                "label": "Discreet manager check",
                "description": "Establish whether a legitimate project explains the access.",
            },
        ],
        "trigger_conditions": {
            "all": [
                {"field": "risk_score", "op": "gte", "value": 60},
                {"field": "vectors.volume", "op": "gte", "value": 60},
            ]
        },
    },
    {
        "slug": "benign-change-suppression",
        "name": "Benign change suppression",
        "description": "Fold an approved change into the baseline so it stops re-alerting.",
        "category": "tuning",
        "estimated_minutes": 5,
        "requires_approval": False,
        "steps": [
            {
                "action": ResponseAction.ADD_CONTEXT_EXEMPTION.value,
                "label": "Record the approval",
                "description": "Attach the change ticket as a scoped context record.",
            },
            {
                "action": ResponseAction.RE_BASELINE.value,
                "label": "Re-learn the baseline",
                "description": "Incorporate the new access pattern as normal.",
            },
        ],
        "trigger_conditions": {},
    },
    {
        "slug": "departing-employee-watch",
        "name": "Departing employee watch",
        "description": "Heightened monitoring during a notice period.",
        "category": "monitoring",
        "estimated_minutes": 8,
        "requires_approval": False,
        "steps": [
            {
                "action": ResponseAction.OPEN_TICKET.value,
                "label": "Open a monitoring case",
                "description": "Track the notice period as a time-boxed case.",
            },
            {
                "action": ResponseAction.NOTIFY_MANAGER.value,
                "label": "Brief the manager",
                "description": "Confirm expected offboarding data handling.",
            },
        ],
        "trigger_conditions": {},
    },
)

# ------------------------------------------------------------------- indicators
INDICATORS: tuple[tuple, ...] = (
    (
        IndicatorType.IP,
        "185.220.101.5",
        92,
        Severity.CRITICAL,
        "tor-exit-nodes",
        "Known Tor exit node observed in credential-stuffing campaigns.",
    ),
    (
        IndicatorType.IP,
        "45.153.160.140",
        85,
        Severity.HIGH,
        "abuse-ch-feodo",
        "Command-and-control infrastructure associated with credential theft.",
    ),
    (
        IndicatorType.IP,
        "103.21.44.9",
        70,
        Severity.MEDIUM,
        "internal-blocklist",
        "Bulletproof hosting range with repeated abuse reports.",
    ),
    (
        IndicatorType.ASN,
        "AS9009",
        65,
        Severity.MEDIUM,
        "internal-blocklist",
        "Hosting ASN frequently used for anonymising proxies.",
    ),
    (
        IndicatorType.USER_AGENT,
        "python-requests/2.28.1",
        55,
        Severity.LOW,
        "internal-blocklist",
        "Scripted client impersonating a browser session.",
    ),
    (IndicatorType.TOR_EXIT, "185.220.100.240", 90, Severity.HIGH, "tor-exit-nodes", "Tor exit node."),
)

# ------------------------------------------------------------------ integrations
INTEGRATIONS: tuple[tuple, ...] = (
    (
        "Okta Workforce Identity",
        IntegrationKind.IDP,
        "Okta",
        IntegrationStatus.CONNECTED,
        "SCIM 2.0 / OAuth 2.0",
        "Real-time webhook",
        24,
        4820,
    ),
    (
        "Microsoft Entra ID",
        IntegrationKind.IDP,
        "Microsoft",
        IntegrationStatus.CONNECTED,
        "Microsoft Graph v1.0",
        "15 minutes",
        24,
        3110,
    ),
    (
        "ServiceNow ITSM",
        IntegrationKind.ITSM,
        "ServiceNow",
        IntegrationStatus.CONNECTED,
        "REST Table API",
        "Bi-directional live",
        142,
        0,
    ),
    (
        "Jira Service Management",
        IntegrationKind.ITSM,
        "Atlassian",
        IntegrationStatus.CONNECTED,
        "REST API v3",
        "5 minutes",
        88,
        0,
    ),
    (
        "Splunk Enterprise",
        IntegrationKind.SIEM,
        "Splunk",
        IntegrationStatus.STREAMING,
        "HTTP Event Collector",
        "Sub-second",
        0,
        41_200,
    ),
    (
        "CrowdStrike Falcon",
        IntegrationKind.EDR,
        "CrowdStrike",
        IntegrationStatus.CONNECTED,
        "Falcon Streaming API",
        "Real-time",
        24,
        9_640,
    ),
    (
        "Workday HRIS",
        IntegrationKind.HRIS,
        "Workday",
        IntegrationStatus.CONNECTED,
        "Workday REST",
        "Hourly",
        24,
        0,
    ),
    (
        "Slack ChatOps",
        IntegrationKind.CHATOPS,
        "Slack",
        IntegrationStatus.CONNECTED,
        "Slack Web API",
        "Real-time",
        1,
        0,
    ),
    (
        "Netskope CASB",
        IntegrationKind.CASB,
        "Netskope",
        IntegrationStatus.DEGRADED,
        "REST API v2",
        "10 minutes",
        24,
        1_180,
    ),
)
