"""initial schema

Revision ID: eec815c421e4
Revises: 
Created: 2026-09-17 18:14:51.496195+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Custom column types (JSONType, StrEnumType) are rendered fully qualified by
# autogenerate, so the package must be importable from the revision itself.
import app.db.types  # noqa: F401
import app.db.types
import sqlalchemy as sa

revision: str = 'eec815c421e4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('owner_team', sa.String(length=96), nullable=False),
    sa.Column('sensitivity_level', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=24), nullable=False),
    sa.Column('contains_pii', sa.Boolean(), nullable=False),
    sa.Column('contains_phi', sa.Boolean(), nullable=False),
    sa.Column('contains_cardholder_data', sa.Boolean(), nullable=False),
    sa.Column('is_crown_jewel', sa.Boolean(), nullable=False),
    sa.Column('record_estimate', sa.Integer(), nullable=False),
    sa.Column('compliance_scopes', app.db.types.JSONType(), nullable=False),
    sa.Column('tags', app.db.types.JSONType(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_sensitivity_level'), ['sensitivity_level'], unique=False)

    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.String(length=48), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=48), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('payload', app.db.types.JSONType(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_ts', ['actor_email', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_id'), ['target_id'], unique=False)

    op.create_table('detection_rules',
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('conditions', app.db.types.JSONType(), nullable=False),
    sa.Column('risk_boost', sa.Float(), nullable=False),
    sa.Column('mitre_techniques', app.db.types.JSONType(), nullable=False),
    sa.Column('recommended_actions', app.db.types.JSONType(), nullable=False),
    sa.Column('suppress_when_context', sa.Boolean(), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('true_positive_count', sa.Integer(), nullable=False),
    sa.Column('false_positive_count', sa.Integer(), nullable=False),
    sa.Column('last_matched_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_rules'))
    )
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_rules_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_slug'), ['slug'], unique=True)

    op.create_table('identities',
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('role_title', sa.String(length=120), nullable=False),
    sa.Column('manager', sa.String(length=160), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('employment_type', sa.String(length=40), nullable=False),
    sa.Column('peer_group_id', sa.String(length=96), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_privileged', sa.Boolean(), nullable=False),
    sa.Column('is_service_account', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_quarantined', sa.Boolean(), nullable=False),
    sa.Column('on_watchlist', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('raw_risk_score', sa.Float(), nullable=False),
    sa.Column('transition_state', sa.String(length=32), nullable=False),
    sa.Column('drift_velocity', sa.Float(), nullable=False),
    sa.Column('dominant_vector', sa.String(length=32), nullable=False),
    sa.Column('vector_scores', app.db.types.JSONType(), nullable=False),
    sa.Column('last_scored_at', sa.DateTime(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('attributes', app.db.types.JSONType(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identities'))
    )
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_identities_department'), ['department'], unique=False)
        batch_op.create_index('ix_identities_dept_risk', ['department', 'risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_identities_peer_group_id'), ['peer_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identities_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index('ix_identities_state', ['transition_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_identities_username'), ['username'], unique=True)

    op.create_table('integrations',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('vendor', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('protocol', sa.String(length=80), nullable=False),
    sa.Column('sync_interval', sa.String(length=48), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('entities_synced', sa.Integer(), nullable=False),
    sa.Column('events_ingested_24h', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config', app.db.types.JSONType(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations'))
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_kind'), ['kind'], unique=False)

    op.create_table('peer_groups',
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('role_title', sa.String(length=120), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('centroid', app.db.types.JSONType(), nullable=False),
    sa.Column('shared_resources', app.db.types.JSONType(), nullable=False),
    sa.Column('mean_risk', sa.Float(), nullable=False),
    sa.Column('stddev_risk', sa.Float(), nullable=False),
    sa.Column('mean_daily_events', sa.Float(), nullable=False),
    sa.Column('mean_max_sensitivity', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_peer_groups'))
    )
    with op.batch_alter_table('peer_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_peer_groups_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_peer_groups_key'), ['key'], unique=True)

    op.create_table('playbooks',
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('steps', app.db.types.JSONType(), nullable=False),
    sa.Column('trigger_conditions', app.db.types.JSONType(), nullable=False),
    sa.Column('auto_execute', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playbooks'))
    )
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playbooks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_playbooks_slug'), ['slug'], unique=True)

    op.create_table('threat_indicators',
    sa.Column('indicator_type', sa.String(length=24), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source_feed', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threat_indicators'))
    )
    with op.batch_alter_table('threat_indicators', schema=None) as batch_op:
        batch_op.create_index('ix_indicators_type_value', ['indicator_type', 'value'], unique=True)
        batch_op.create_index(batch_op.f('ix_threat_indicators_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_threat_indicators_value'), ['value'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('preferences', app.db.types.JSONType(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('api_keys',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=24), nullable=False),
    sa.Column('owner_id', sa.String(length=48), nullable=False),
    sa.Column('scopes', app.db.types.JSONType(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_api_keys_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_owner_id'), ['owner_id'], unique=False)

    op.create_table('baselines',
    sa.Column('identity_id', sa.String(length=48), nullable=False),
    sa.Column('hourly_distribution', app.db.types.JSONType(), nullable=False),
    sa.Column('dow_distribution', app.db.types.JSONType(), nullable=False),
    sa.Column('common_resources', app.db.types.JSONType(), nullable=False),
    sa.Column('resource_frequencies', app.db.types.JSONType(), nullable=False),
    sa.Column('known_ip_prefixes', app.db.types.JSONType(), nullable=False),
    sa.Column('known_countries', app.db.types.JSONType(), nullable=False),
    sa.Column('known_devices', app.db.types.JSONType(), nullable=False),
    sa.Column('action_frequencies', app.db.types.JSONType(), nullable=False),
    sa.Column('resource_entropy', sa.Float(), nullable=False),
    sa.Column('avg_daily_events', sa.Float(), nullable=False),
    sa.Column('stddev_daily_events', sa.Float(), nullable=False),
    sa.Column('avg_daily_bytes', sa.Float(), nullable=False),
    sa.Column('stddev_daily_bytes', sa.Float(), nullable=False),
    sa.Column('typical_max_sensitivity', sa.Integer(), nullable=False),
    sa.Column('off_hours_ratio', sa.Float(), nullable=False),
    sa.Column('sample_event_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('maturity', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], name=op.f('fk_baselines_identity_id_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baselines'))
    )
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baselines_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_baselines_identity_id'), ['identity_id'], unique=True)

    op.create_table('cases',
    sa.Column('reference', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('primary_identity_id', sa.String(length=48), nullable=True),
    sa.Column('assignee_id', sa.String(length=48), nullable=True),
    sa.Column('opened_by_id', sa.String(length=48), nullable=True),
    sa.Column('tags', app.db.types.JSONType(), nullable=False),
    sa.Column('mitre_techniques', app.db.types.JSONType(), nullable=False),
    sa.Column('peak_risk_score', sa.Float(), nullable=False),
    sa.Column('blast_radius_score', sa.Float(), nullable=False),
    sa.Column('estimated_records_at_risk', sa.Integer(), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('contained_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closure_reason', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_cases_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], name=op.f('fk_cases_opened_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_identity_id'], ['identities.id'], name=op.f('fk_cases_primary_identity_id_identities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_primary_identity_id'), ['primary_identity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)
        batch_op.create_index('ix_cases_status_priority', ['status', 'priority'], unique=False)

    op.create_table('context_records',
    sa.Column('identity_id', sa.String(length=48), nullable=False),
    sa.Column('context_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ticket_reference', sa.String(length=80), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('damping_factor', sa.Float(), nullable=False),
    sa.Column('target_resources', app.db.types.JSONType(), nullable=False),
    sa.Column('allowed_actions', app.db.types.JSONType(), nullable=False),
    sa.Column('approved_by', sa.String(length=160), nullable=False),
    sa.Column('created_by_id', sa.String(length=48), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('applied_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_context_records_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], name=op.f('fk_context_records_identity_id_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_context_records'))
    )
    with op.batch_alter_table('context_records', schema=None) as batch_op:
        batch_op.create_index('ix_context_identity_window', ['identity_id', 'valid_from', 'valid_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_records_context_type'), ['context_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_records_identity_id'), ['identity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_records_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_records_ticket_reference'), ['ticket_reference'], unique=False)

    op.create_table('risk_snapshots',
    sa.Column('identity_id', sa.String(length=48), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('raw_risk_score', sa.Float(), nullable=False),
    sa.Column('transition_state', sa.String(length=32), nullable=False),
    sa.Column('vector_scores', app.db.types.JSONType(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], name=op.f('fk_risk_snapshots_identity_id_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_snapshots'))
    )
    with op.batch_alter_table('risk_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_snapshots_identity_id'), ['identity_id'], unique=False)
        batch_op.create_index('ix_snapshots_identity_ts', ['identity_id', 'captured_at'], unique=False)

    op.create_table('security_events',
    sa.Column('identity_id', sa.String(length=48), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('sensitivity_level', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=4), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('asn', sa.String(length=48), nullable=True),
    sa.Column('device_id', sa.String(length=96), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('bytes_transferred', sa.Integer(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('is_off_hours', sa.Boolean(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('damped_score', sa.Float(), nullable=False),
    sa.Column('vector_scores', app.db.types.JSONType(), nullable=False),
    sa.Column('is_damped', sa.Boolean(), nullable=False),
    sa.Column('damping_reason', sa.Text(), nullable=True),
    sa.Column('matched_rules', app.db.types.JSONType(), nullable=False),
    sa.Column('context_tags', app.db.types.JSONType(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('event_metadata', app.db.types.JSONType(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], name=op.f('fk_security_events_identity_id_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_identity_ts', ['identity_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_events_resource_ts', ['resource', 'occurred_at'], unique=False)
        batch_op.create_index('ix_events_score', ['anomaly_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_identity_id'), ['identity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_resource'), ['resource'], unique=False)

    op.create_table('watchlists',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('risk_multiplier', sa.Float(), nullable=False),
    sa.Column('member_ids', app.db.types.JSONType(), nullable=False),
    sa.Column('created_by_id', sa.String(length=48), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_watchlists_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlists')),
    sa.UniqueConstraint('name', name=op.f('uq_watchlists_name'))
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlists_created_at'), ['created_at'], unique=False)

    op.create_table('alerts',
    sa.Column('identity_id', sa.String(length=48), nullable=False),
    sa.Column('case_id', sa.String(length=48), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('raw_risk_score', sa.Float(), nullable=False),
    sa.Column('transition_state', sa.String(length=32), nullable=False),
    sa.Column('drift_velocity', sa.Float(), nullable=False),
    sa.Column('context_damped', sa.Boolean(), nullable=False),
    sa.Column('damping_reason', sa.Text(), nullable=True),
    sa.Column('anti_tamper_override', sa.Boolean(), nullable=False),
    sa.Column('dominant_vectors', app.db.types.JSONType(), nullable=False),
    sa.Column('vector_scores', app.db.types.JSONType(), nullable=False),
    sa.Column('mitre_techniques', app.db.types.JSONType(), nullable=False),
    sa.Column('triggering_event_ids', app.db.types.JSONType(), nullable=False),
    sa.Column('matched_rule_ids', app.db.types.JSONType(), nullable=False),
    sa.Column('assigned_to_id', sa.String(length=48), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_alerts_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_alerts_case_id_cases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], name=op.f('fk_alerts_identity_id_identities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_context_damped'), ['context_damped'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_alerts_identity_created', ['identity_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_identity_id'), ['identity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index('ix_alerts_status_risk', ['status', 'risk_score'], unique=False)

    op.create_table('case_entries',
    sa.Column('case_id', sa.String(length=48), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('author_id', sa.String(length=48), nullable=True),
    sa.Column('author_label', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entry_metadata', app.db.types.JSONType(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_case_entries_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_entries_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_entries'))
    )
    with op.batch_alter_table('case_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_entries_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_entries_created_at'), ['created_at'], unique=False)

    op.create_table('action_records',
    sa.Column('identity_id', sa.String(length=48), nullable=False),
    sa.Column('alert_id', sa.String(length=48), nullable=True),
    sa.Column('case_id', sa.String(length=48), nullable=True),
    sa.Column('playbook_id', sa.String(length=48), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('performed_by_id', sa.String(length=48), nullable=True),
    sa.Column('performed_by_label', sa.String(length=160), nullable=False),
    sa.Column('is_automated', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('result', app.db.types.JSONType(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_action_records_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_action_records_case_id_cases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], name=op.f('fk_action_records_identity_id_identities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], name=op.f('fk_action_records_performed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], name=op.f('fk_action_records_playbook_id_playbooks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_records'))
    )
    with op.batch_alter_table('action_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_records_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_records_identity_id'), ['identity_id'], unique=False)
        batch_op.create_index('ix_actions_identity_created', ['identity_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_records', schema=None) as batch_op:
        batch_op.drop_index('ix_actions_identity_created')
        batch_op.drop_index(batch_op.f('ix_action_records_identity_id'))
        batch_op.drop_index(batch_op.f('ix_action_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_action_records_action'))

    op.drop_table('action_records')
    with op.batch_alter_table('case_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_case_entries_case_id'))

    op.drop_table('case_entries')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_status_risk')
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_risk_score'))
        batch_op.drop_index(batch_op.f('ix_alerts_identity_id'))
        batch_op.drop_index('ix_alerts_identity_created')
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_context_damped'))
        batch_op.drop_index(batch_op.f('ix_alerts_case_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlists_created_at'))

    op.drop_table('watchlists')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_resource'))
        batch_op.drop_index(batch_op.f('ix_security_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_security_events_identity_id'))
        batch_op.drop_index(batch_op.f('ix_security_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_security_events_action'))
        batch_op.drop_index('ix_events_score')
        batch_op.drop_index('ix_events_resource_ts')
        batch_op.drop_index('ix_events_identity_ts')

    op.drop_table('security_events')
    with op.batch_alter_table('risk_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_identity_ts')
        batch_op.drop_index(batch_op.f('ix_risk_snapshots_identity_id'))
        batch_op.drop_index(batch_op.f('ix_risk_snapshots_captured_at'))

    op.drop_table('risk_snapshots')
    with op.batch_alter_table('context_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_records_ticket_reference'))
        batch_op.drop_index(batch_op.f('ix_context_records_is_active'))
        batch_op.drop_index(batch_op.f('ix_context_records_identity_id'))
        batch_op.drop_index(batch_op.f('ix_context_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_context_records_context_type'))
        batch_op.drop_index('ix_context_identity_window')

    op.drop_table('context_records')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index('ix_cases_status_priority')
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_reference'))
        batch_op.drop_index(batch_op.f('ix_cases_primary_identity_id'))
        batch_op.drop_index(batch_op.f('ix_cases_created_at'))
        batch_op.drop_index(batch_op.f('ix_cases_assignee_id'))

    op.drop_table('cases')
    with op.batch_alter_table('baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baselines_identity_id'))
        batch_op.drop_index(batch_op.f('ix_baselines_created_at'))

    op.drop_table('baselines')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_owner_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_created_at'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('threat_indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_indicators_value'))
        batch_op.drop_index(batch_op.f('ix_threat_indicators_created_at'))
        batch_op.drop_index('ix_indicators_type_value')

    op.drop_table('threat_indicators')
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playbooks_slug'))
        batch_op.drop_index(batch_op.f('ix_playbooks_created_at'))

    op.drop_table('playbooks')
    with op.batch_alter_table('peer_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_peer_groups_key'))
        batch_op.drop_index(batch_op.f('ix_peer_groups_created_at'))

    op.drop_table('peer_groups')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_kind'))
        batch_op.drop_index(batch_op.f('ix_integrations_created_at'))

    op.drop_table('integrations')
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identities_username'))
        batch_op.drop_index('ix_identities_state')
        batch_op.drop_index(batch_op.f('ix_identities_risk_score'))
        batch_op.drop_index(batch_op.f('ix_identities_peer_group_id'))
        batch_op.drop_index('ix_identities_dept_risk')
        batch_op.drop_index(batch_op.f('ix_identities_department'))
        batch_op.drop_index(batch_op.f('ix_identities_created_at'))

    op.drop_table('identities')
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_rules_slug'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_enabled'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_created_at'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_category'))

    op.drop_table('detection_rules')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('ix_audit_logs_actor_ts')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_sensitivity_level'))
        batch_op.drop_index(batch_op.f('ix_assets_key'))
        batch_op.drop_index(batch_op.f('ix_assets_created_at'))
        batch_op.drop_index(batch_op.f('ix_assets_category'))

    op.drop_table('assets')
    # ### end Alembic commands ###
